<?php

/**
 * $Id: params.php 43 2015-12-08 14:32:20Z chrdel $
 *          
 * EXCLUSIVE LICENSE
 * THE INFORMATION AND COMPUTER SOURCE CODE CONTAINED WITHIN THIS PROGRAM SCRIPT IS
 * THE EXCLUSIVE PROPERTY OF HEALTHFIRST FINANCIAL, LLC. USE MUST BE AUTHORIZED UNDER WRITTEN
 * LICENSE OBTAINED FROM HEALTHFIRST FINANCIAL, LLC. USE AT YOUR OWN RISK. NO WARANTY EITHER
 * EXPRESSED OR IMPLIED.
 *
 * UNAUTHORIZED USE, ALTERATION, COPYING, OR REDISTRIBUTION IS STRICTLY PROHIBITED.
 *
 * @copyright Copyright (c) 2015 HealthFirst Financial, LLC.
 *
 * @author KG Financial Software Pvt Ltd (www.kgfsl.com), Chris DeLess
 *
 */
return array(
   
   
);
